### ISSUE TITLE
Biosights: Focus to scanned bio

### ISSUE THREAD

**Issue by nyenyon** [Xjph/ObservatoryCore#123]
Hi,

wenever i habe a system with a lot of planets with biossignals, i have a scroll-issue. Here an example:

whenever i scan a biosignal the list jumps down:
![image](https://github.com/Xjph/ObservatoryCore/assets/137694071/12bb858b-a0d7-482e-b735-7a9894969fcc)

The scanned biosign is here:
![image](https://github.com/Xjph/ObservatoryCore/assets/137694071/d8fd35d0-504e-4f07-8c44-4d79c6558866)

It would be nice, if the list scrolls to the planet line...?

**Comment by fredjk-gh** [comment]
So, yeah. This is a bit of a frustrating bit of the current implementation and it's complicated. Bottom line: Plugins have no control over scroll position today.

Here are the moving parts as to why it's not trivial to solve.

1) When viewing a plugin (ie. Explorer) while scanning things, new content is appended to the bottom of the list, so everything would scroll off the bottom out of sight. To deal with this, a "scroll-to-bottom" mechanism was implemented to keep that in view. It works so long as you always look at the same plugin.
2) However, switching plugins redraws the grid resulting in the content being scrolled to the top because we couldn't find a way to scroll that to the bottom after switching plugins with Avalonia to keep it consistent.
3) Matt's BioInsights plugin is a little more advanced and redraws the *whole grid* every time and in so doing, sorts the list -- so new stuff doesn't necessarily appear at the bottom -- and in thus it doesn't work well with the "scroll-to-bottom" behavior. Matt has implemented options to position the most recently scanned body where you want it in an attempt to help with this -- so you could position it at the bottom -- which works unless you switch between plugins a lot. Or you could position it at the top -- but that doesn't play well with scroll-to-bottom.

We could disable scroll-to-bottom -- but then all the other plugins have to do something to keep their content from scrolling off the bottom -- or you have to constantly scroll to see new stuff in plugins other than BioInsights. Several plugins offer a "show current system data only" option to help keep the size of the content to a minimum in order to reduce scrolling, but with some systems that doesn't help much. Consider enabling that option where available.

The good news is: there is a UI rewrite underway which replaces the Avalonia implementation with a classic WinForms -- we hope to solve this problem for good by offering a bit more flexibility and control over the UI from each plugin. I hear the UI rewrite should be ready for plugin developers to fiddle with Soon (TM). 😄 

This was a far longer answer than was necessary. But all this to say: we're well aware and want to fix this too!

**Comment by nyenyon** [comment]
Thanx for this really deep extensive anwser. It's perfect you have that issue on your radar.
