### ISSUE TITLE
Main window out of desktop bounds

### ISSUE THREAD

**Issue by parduz** [Xjph/ObservatoryCore#124]
![image](https://github.com/Xjph/ObservatoryCore/assets/9556348/71a5ef33-28ab-4381-9cfd-bc96f2c9cb31)
I've changed my monitors, and now Observatory core window is out fo screen bound and i cannot move/resize/minimize it.

![image](https://github.com/Xjph/ObservatoryCore/assets/9556348/1438210d-7562-4701-9c3c-5e8656eb9e5a)

I think that at the launch the program should check its saved position, and "reset" to main screen and a safe size if the check fails.

**Comment by wbovela** [comment]
If you have two monitors, each with a different resolution, and move the application to the second monitor and resize it there, things go wrong despite your settings being saved. The saved values for size and position appear to be relative to your main display. Moving the window to your main display manually before closing the application helps. But obviously requires doing this every time.
The position and size of the window should be calculated relative to the active display instead of just the main display.

**Comment by ejrgithub** [comment]
Thanks for that info. I hope this issue gets fixed, OC is a really great program, but honestly this is frustrating.

**Comment by Xjph** [comment]
The newest version should try to restore its position while also ensuring that it is kept on screen.
