### ISSUE TITLE
Journal Read Errors

### ISSUE THREAD

**Issue by nlabiris** [Xjph/ObservatoryCore#40]
Hello,

When clicking at the "Read All" button, a window named "Journal Read Errors" appears with a few errors:

![image](https://user-images.githubusercontent.com/13470357/143783468-036ba82b-3848-4461-ad36-fc83814cd8f2.png)

After closing that window, everything seems to work fine though.

I have version 0.1.299.2250

Do you want me to upload all my journal files, because this window may indicate some of them? I will upload at least the ones that are indicated.

Thank you
[Journal.210714211610.01.log](https://github.com/Xjph/ObservatoryCore/files/7614252/Journal.210714211610.01.log)
[Journal.210709230655.01.log](https://github.com/Xjph/ObservatoryCore/files/7614253/Journal.210709230655.01.log)
[Journal.210605224343.01.log](https://github.com/Xjph/ObservatoryCore/files/7614254/Journal.210605224343.01.log)
[Journal.210717171154.01.log](https://github.com/Xjph/ObservatoryCore/files/7614255/Journal.210717171154.01.log)
[Journal.210715192011.01.log](https://github.com/Xjph/ObservatoryCore/files/7614256/Journal.210715192011.01.log)

.

**Comment by Xjph** [comment]
Congratulations! You appear to be the first ever person who's used Observatory Core with `PowerplayVoucher` events in your logs!

(Or no-one else reported the errors)

Your journal files have exactly what I need to fix this, so it'll be sorted out for next release.  In the meantime you should be able to dismiss this error and use Observatory without issue otherwise.

**Comment by Xjph** [comment]
714537e58aaeb6f2d5dbaca063bc97aad87a1ce8
