### ISSUE TITLE
ObservatoryCore exits silently if ObservatoryHerald.dll is in the plugin folder

### ISSUE THREAD

**Issue by TribbleTrouble** [Xjph/ObservatoryCore#99]
Observatorycore appears to exit silently on startup.

If I delete ObservatoryHerald.dll the observatory core  starts as expected.

I have tried reinstalling the latest release, but still does not work.

**Comment by BurnGerRubber** [comment]
Have the same issue, in taskmanager you find the exe from Observatorycore for a cupple of seconds, and then it died silently. After delete the herald.dll observatory starts normaly.

**Comment by fredjk-gh** [comment]
Xjph is aware of this and it has been discussed in discord a bit. This is due to some interesting internet routing issues preventing contact with the service that backs that plugin. That said, it should fail more gracefully than crashing the whole application. Xjph was hoping on working on a solution asap. So stay tuned!

The current recommended work around is to move the ObservatoryHerald.dll out of the plugins/ folder (or rename it to .bak or something like that) so it's not recognized as a plugin anymore.

**Comment by pgrimstrup** [comment]
Is this issue being worked on? I have forked the code and created a fix locally (improved exception handling) among other issues (mixing async and Threading, improve async calls in general, improve the notification queue).

It is definitely due to a network or server error. The API endpoint can no longer be reached.

**Comment by Xjph** [comment]
Man, I need to look through these more often.

Failure by Herald to reach its api endpoint should now surface an error to the user and not crash observatory.

**Comment by fredjk-gh** [comment]
Indeed, so should I. I think https://github.com/Xjph/ObservatoryCore/pull/151 should have addressed this.
